name: Rust

on:
  push:
    paths:
      - 'client/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        directory: ['client']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      working-directory: ${{ matrix.directory }}
      run: cargo build --release

    - name: Archive production artifacts
      working-directory: ${{ matrix.directory }}
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          7z a client-${{ matrix.os }}.zip ./target/release
        else
          tar -cvf client-${{ matrix.os }}.tar ./target/release
          gzip client-${{ matrix.os }}.tar
        fi

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-client
        path: ${{ matrix.directory }}/client-${{ matrix.os }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Get version
      id: get_version
      run: echo "::set-output name=version::$(cat misc/version)"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.release_token }}
      with:
        tag_name: client-${{ steps.get_version.outputs.version }}
        release_name: client-${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.release_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ubuntu-latest-client/client-ubuntu-latest.tar.gz
        asset_name: ubuntu-latest-client-${{ steps.get_version.outputs.version }}.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.release_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./windows-latest-client/client-windows-latest.zip
        asset_name: windows-latest-client-${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.release_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./macos-latest-client/client-macos-latest.tar.gz
        asset_name: macos-latest-client-${{ steps.get_version.outputs.version }}.tar.gz
        asset_content_type: application/gzip